name: 6-Hour Config Sync

on:
  schedule:
    - cron: '0 */6 * * *' # هر ۶ ساعت یک‌بار
  workflow_dispatch: # امکان اجرای دستی

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه به گیت‌هاب برای ذخیره کردن نتایج در مخزن
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Collector
        run: python collector.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add telegram_configs.txt telegram_configs_base64.txt
          git commit -m "Update configs: $(date)" || echo "No changes"
          git push
